# Site settings
title: Christopher Wells
email: cwellsny@nycap.rr.com
description: "My name is Christopher Wells, and I am an aspiring computer programmer. I am a student at SUNY Oswego, and am pursuing a degree in Computer Science."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://excaliburzero.github.io" # the base hostname & protocol for your site
twitter_username: ExcaliburZero_Z
github_username:  ExcaliburZero
stackoverflowcareers_username: christopherrandallwells

# Set post urls to not use categories
permalink: /blog/:year/:month/:day/:title.html

# Build settings
markdown: kramdown

# Ignore Divshot file
exclude:
  - divshot.json

# Gems
gems:
  - jekyll-sitemap # Generate sitemap for website
